# Generated by Django 4.1 on 2022-08-24 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User_Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Bio", models.CharField(max_length=200)),
                (
                    "Username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blogapp.user"
                    ),
                ),
            ],
            options={
                "db_table": "User_Profile",
            },
        ),
    ]
