# Generated by Django 4.1 on 2022-08-24 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0002_user_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Programming_Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Blog_Title", models.CharField(max_length=100)),
                ("Published_Date_Time", models.CharField(max_length=100)),
                ("Blog_content", models.CharField(max_length=500)),
                (
                    "Username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blogapp.user"
                    ),
                ),
            ],
            options={
                "db_table": "Programming_Blog",
            },
        ),
        migrations.CreateModel(
            name="Gaming_Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Blog_Title", models.CharField(max_length=100)),
                ("Published_Date_Time", models.CharField(max_length=100)),
                ("Blog_content", models.CharField(max_length=500)),
                (
                    "Username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blogapp.user"
                    ),
                ),
            ],
            options={
                "db_table": "Gaming_Blog",
            },
        ),
        migrations.CreateModel(
            name="Database_Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Blog_Title", models.CharField(max_length=100)),
                ("Published_Date_Time", models.CharField(max_length=100)),
                ("Blog_content", models.CharField(max_length=500)),
                (
                    "Username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blogapp.user"
                    ),
                ),
            ],
            options={
                "db_table": "Database_Blog",
            },
        ),
        migrations.CreateModel(
            name="Computer_Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Blog_Title", models.CharField(max_length=100)),
                ("Published_Date_Time", models.CharField(max_length=100)),
                ("Blog_content", models.CharField(max_length=500)),
                (
                    "Username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blogapp.user"
                    ),
                ),
            ],
            options={
                "db_table": "Computer_Blog",
            },
        ),
        migrations.CreateModel(
            name="Business_Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Blog_Title", models.CharField(max_length=100)),
                ("Published_Date_Time", models.CharField(max_length=100)),
                ("Blog_content", models.CharField(max_length=500)),
                (
                    "Username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blogapp.user"
                    ),
                ),
            ],
            options={
                "db_table": "Business_Blog",
            },
        ),
    ]
