# Generated by Django 4.1 on 2022-08-24 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0003_programming_blog_gaming_blog_database_blog_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="business_blog",
            name="id",
        ),
        migrations.RemoveField(
            model_name="computer_blog",
            name="id",
        ),
        migrations.RemoveField(
            model_name="database_blog",
            name="id",
        ),
        migrations.RemoveField(
            model_name="gaming_blog",
            name="id",
        ),
        migrations.RemoveField(
            model_name="programming_blog",
            name="id",
        ),
        migrations.RemoveField(
            model_name="user_profile",
            name="id",
        ),
        migrations.AlterField(
            model_name="business_blog",
            name="Username",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="blogapp.user",
            ),
        ),
        migrations.AlterField(
            model_name="computer_blog",
            name="Username",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="blogapp.user",
            ),
        ),
        migrations.AlterField(
            model_name="database_blog",
            name="Username",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="blogapp.user",
            ),
        ),
        migrations.AlterField(
            model_name="gaming_blog",
            name="Username",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="blogapp.user",
            ),
        ),
        migrations.AlterField(
            model_name="programming_blog",
            name="Username",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="blogapp.user",
            ),
        ),
        migrations.AlterField(
            model_name="user_profile",
            name="Username",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="blogapp.user",
            ),
        ),
    ]
