# Generated by Django 4.1 on 2022-08-24 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0004_remove_business_blog_id_remove_computer_blog_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="business_blog",
            old_name="Blog_content",
            new_name="Blog_Content",
        ),
        migrations.RenameField(
            model_name="computer_blog",
            old_name="Blog_content",
            new_name="Blog_Content",
        ),
        migrations.RenameField(
            model_name="database_blog",
            old_name="Blog_content",
            new_name="Blog_Content",
        ),
        migrations.RenameField(
            model_name="gaming_blog",
            old_name="Blog_content",
            new_name="Blog_Content",
        ),
        migrations.RenameField(
            model_name="programming_blog",
            old_name="Blog_content",
            new_name="Blog_Content",
        ),
    ]
