# Generated by Django 2.1.15 on 2022-08-29 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='athor',
            new_name='author',
        ),
    ]
