# Generated by Django 2.1.15 on 2022-08-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20220829_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='BLOGGER', max_length=256),
        ),
    ]
